### ISSUE TITLE
install latest version

### ISSUE THREAD

**Issue by jimr6007-placeiq** [puppet-community/puppetboard#101]
sorry for the nob question but when I install via pip or the puppet forge module with the "latest" param set, I end up with a very old version of puppetboard. I can tell because many part of the UI are broken and in the bottom right of the screen I see 2013 not 2013-2014.
I'm installing on Centos 6.6/python is 2.6
Any suggestions on what to look at, what I might be doing wrong?

Thanks for the great work on this tool by the way !

**Comment by fgimian** [comment]
Duplicate of #131 :smile:
