### ISSUE TITLE
PuppetDB Issue

### ISSUE THREAD

**Issue by aeekayy** [puppet-community/puppetboard#112]
I'm having a problem connecting to PuppetDB when accessing the website.  We I hit Puppetboard via browser, I see an `Internal Server Error: We were unable to reach PuppetDB`.  When I look at the logs on the server, this is what I see:

```
[Tue Jan 06 13:24:14 2015] [error] INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
[Tue Jan 06 13:24:14 2015] [error] ERROR:pypuppetdb.api:Could not reach PuppetDB on localhost:8080 over HTTP.
```

PuppetDB is running and I'm able to retrieve query results when I cURL queries on the server.  Any thoughts on what might be the issue?  Here's my settings.py file 
```
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = '127.0.0.1'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = None
PUPPETDB_CERT = None
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 1
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
PUPPETDB_EXPERIMENTAL = False
REPORTS_COUNT = 10
```

**Comment by corey-hammerton** [comment]
What port(s) is the PuppetDB listening on?

**Comment by aeekayy** [comment]
I have PuppetDB listening on port 8080:
netstat: `tcp        0      0 ::ffff:127.0.0.1:8080       :::*                        LISTEN      1575/java    `
ps: `puppetdb  1575  0.3  2.2 4842272 272012 ?      Sl   Jan05   5:24 /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java -XX:OnOutOfMemoryError=kill -9 %p -Xmx192m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/puppetdb/puppetdb-oom.hprof -Djava.security.egd=file:/dev/urandom -cp /usr/share/puppetdb/puppetdb.jar clojure.main -m com.puppetlabs.puppetdb.core services -c /etc/puppetdb/conf.d`

**Comment by daenney** [comment]
If PuppetDB and Puppetboard are on the same machine this should work.

**Comment by aeekayy** [comment]
They are but I'm still getting the error.  Any ideas on how to troubleshoot this?  I've tried testing pypuppetdb directly and I'm able to get results using that.  Not sure what's the cause, I'm pretty sure it's user error but now I'm stumped as to where the issue could be coming from.

**Comment by daenney** [comment]
Generally that error is only ever thrown if the SSL stuff is in the mix but you're connecting to 127.0.0.1 and haven't set `SSL_KEY` or `SSL_CERT` so it won't be switching to that.

Can you throw away your `settings.py`? Your settings don't look any different from the defaults so it should work 'out of the box'.

**Comment by aeekayy** [comment]
It's a selinux issue. Not sure what it is exactly but at least I've pinpointed the issue. Thanks for the help. I think I can figure it out from here.

**Comment by daenney** [comment]
Awesome, If you do figure it out, safe for disabling SELinux, can you update this issue? It's bound to help someone along the way.

**Comment by aeekayy** [comment]
chcon -Rv --type=httpd_sys_content_t /etc/httpd solved the problem.  /var/run/wsgi runs within /etc/httpd so I had to apply httpd_sys_content_t to the Apache application folder after installing Puppetboard.

**Comment by billjamzz** [comment]
I have similar problem to this.  puppetdb and puppetboard are on same host, curl queries work fine, but puppetboard logs this:
[Fri Oct 16 16:24:27 2015] [error] INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
[Fri Oct 16 16:24:27 2015] [error] ERROR:pypuppetdb.api: localhost:8080 over HTTP.

Not using SELinux.
[root@puppetdb puppetboard]# cat settings.py 
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = 'localhost'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 3
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
PUPPETDB_EXPERIMENTAL = False
REPORTS_COUNT = 10

this command works fine:  curl http://localhost:8080/pdb/query/v4/nodes
I tried removing settings.py, didn't help.
What else should I try?

Using centos6, apache::mod::wsgi, puppetdb 3.1

**Comment by corey-hammerton** [comment]
@billjamzz yours is a case of you using PuppetDB 3.x when pypuppetdb and puppetboard don't yet support it. New versions of those packages will soon be available that will support (only) PuppetDB 3.x and above.

**Comment by billjamzz** [comment]
Thank you for the input.  Any idea on how soon "soon" is? week, months, days, etc?

**Comment by billjamzz** [comment]
btw, pypuppetdb now supports puppetdb 3.x (api v4).  How about puppetboard? (still using api v3)

**Comment by corey-hammerton** [comment]
Keep an eye on https://github.com/puppet-community/puppetboard/pull/176. I have additional updates and fixes to do for it. After it is merged we can release 0.1.0 which supports ONLY PuppetDB 3.x and api v4

**Comment by nix-power** [comment]
Hi, I am using V3 API on my PuppetDB and each time i get error from unicorn: 404 Not Found
Any Direction please? 
(pboard)pboard@pgdb1:/opt/venvs/pboard/lib/python2.7/site-packages/puppetboard$ pip freeze
Flask==0.11
Flask-WTF==0.9.5
Jinja2==2.8
MarkupSafe==0.23
WTForms==1.0.5
Werkzeug==0.11.10
argparse==1.2.1
click==6.6
gunicorn==19.6.0
itsdangerous==0.24
puppetboard==0.1.3
pypuppetdb==0.2.3
requests==2.10.0
urllib3==1.15.1
wsgiref==0.1.2

**Comment by nix-power** [comment]
Perhaps V3 is not supported in this version anymore... sad

**Comment by daenney** [comment]
It's not sad, it's a question of priorities. This is an open source project and as such people only have a limited amount of time to spend on things. Maintaining two versions of the API and staying feature-compatible between the two is enormous amount of work especially since v4 API changed around quite a few things.

If you want to stay on an older version of PuppetDB that doesn't support the v4 API, which has been available for at least a year now, you're free to use an older version of Puppetboard and pypuppetdb.
