### ISSUE TITLE
Problem with CSS. Menu panel hides number of nodes.

### ISSUE THREAD

**Issue by ErikOlufson** [puppet-community/puppetboard#113]
Hello,

CSS has a bug. It has been tested on several brower. For example on Firefox 34.0. The menu panel hides the number of nodes. See screens.

Here the panel is shown and hiding number of nodes.
![auswahl_284](https://cloud.githubusercontent.com/assets/10501646/5706099/513cd6ec-9a7e-11e4-8684-9436b0d921ad.png)

Here the panel has been deactivated via display:none and the number of node is shown.
![auswahl_285](https://cloud.githubusercontent.com/assets/10501646/5706098/513ae288-9a7e-11e4-88fa-bbba32c36dff.png)

**Comment by daenney** [comment]
I hate browsers. Every time they change something...

**Comment by ErikOlufson** [comment]
We have fixed it locally by adding css dirty to ./puppetboard/static/css/puppetboard.css . Added 
.navbar + .container-fluid {
  margin-top: 60px;
}

Maybe you could add it in the css file you prefer.

Regards.

(Hate browsers too ...)

**Comment by propyless** [comment]
Hey there, i was also experiencing this issue. Its not your fault daenney, its the apache conf not allowing access to the statics folder.

You have to add some more conf for apache:

<Directory /usr/lib/python2.6/site-packages/puppetboard/static>
    Satisfy Any
    Allow from all
</Directory>

**Comment by daenney** [comment]
@propyless Oh thanks! I'll add it to the README!

**Comment by propyless** [comment]
no problem, er, I can also add that the query function, sort-by buttons on the tables etc don't work if you dont allow the static files to be accessed since the .js files are inaccessible. I saw a ticket about it before (sort tables stopped functioning) so they might be related to this same issue. I think its issue number 88.
