### ISSUE TITLE
Adding Upgrade instructions

### ISSUE THREAD

**Issue by dklueh** [puppet-community/puppetboard#121]
Could you please add instructions for upgrading an installtion to the latest?

**Comment by daenney** [comment]
`pip install -U puppetboard` or `git pull`?

What sort of instructions are you looking for?

**Comment by dklueh** [comment]
And what about the configs? Do I have to upgrade those, too?

**Comment by daenney** [comment]
Normally no. We ship with a bunch of defaults which you would get when you update so any configuration option you've specified / override would be kept. If there's new settings they'll show up in release notes.

**Comment by centric-jim** [comment]
I'm an early adopter of puppetboard, the version we're running is from Nov 2013, v.0.0.2 and would be interested in knowing if there are any gotchas when going to v0.0.4.

**Comment by daenney** [comment]
Have a look at the changeling: https://github.com/puppet-community/puppetboard/blob/master/CHANGELOG.rst
