### ISSUE TITLE
nodes with status failed not visible 

### ISSUE THREAD

**Issue by dklueh** [puppet-community/puppetboard#125]
The nodes with status failed are not visible, see picture. 
![puppetboard - iron](https://cloud.githubusercontent.com/assets/3582803/6501991/71b24fa0-c31f-11e4-8517-f221a1dfbef4.png)

And: where can I see the version of PuppetBoard?

**Comment by daenney** [comment]
How are they not visible? I'm seeing one node with a failed resource.

**Comment by daenney** [comment]
Oh wait, the static assets. Are you using apache by any chance?

**Comment by dklueh** [comment]
Above the 15 it should be shown, but it isn't.

Yes, Apache:
Server Version: Apache/2.4.7 (Ubuntu) Phusion_Passenger/4.0.37 OpenSSL/1.0.1f
    mod_wsgi/3.4 Python/2.7.6

**Comment by daenney** [comment]
Do you have this stanza in your vhost?

```
    Alias /static /usr/local/lib/pythonX.Y/dist-packages/puppetboard/static
    <Directory /usr/lib/python2.X/dist-packages/puppetboard/static>
        Satisfy Any
        Allow from all
    </Directory>
```

**Comment by dklueh** [comment]
Great! This was my fault. I had:
    <Directory /usr/local/lib/python2.7/dist-packages/puppetboard>
        WSGIProcessGroup puppetboard
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>

That doesn't work! 

Thanx!
