### ISSUE TITLE
Selwscting "Reports" in top-menue empty, but a host has a report

### ISSUE THREAD

**Issue by dklueh** [puppet-community/puppetboard#126]
When selecting the "Reports" in top-menue, the body is empty- no reports are shown here.
But when selcting the report from a host directly, the report is  available.

**Comment by daenney** [comment]
That's because of a static asset not loading causing you not to see this error message

```
Pending #21600. You can access reports for a node or individual reports through the Nodes tab.
```

This is usually an misconfiguration in Apache.

**Comment by bschonec** [comment]
I'm experiencing the same issue.  I know this is rather old but what is the misconfiguration in Apache to which you are referring, @daenney ?
