### ISSUE TITLE
is there any plan to release new version ?

### ISSUE THREAD

**Issue by k2patel** [puppet-community/puppetboard#131]
Hi,

It seems like there is lot more happening here.
But last version released is almost more then year to tag 0.0.4 in python packages.

Is there any plan to release new version to python package or have to use github pull to stay up to date ?

Thanx

**Comment by anarcat** [comment]
i guess this will depend on the new maintainer, see #132

**Comment by fgimian** [comment]
Would be lovely to see a new release prior to the handover if possible guys.  It's a lovely interface and we would love to start using it :smile:

**Comment by corey-hammerton** [comment]
0.0.5 was released last week. 
We are planning on releasing a 0.1.0 release in the near future.
