### ISSUE TITLE
Auto - Refresh

### ISSUE THREAD

**Issue by centric-jim** [puppet-community/puppetboard#143]
Hope this question hasn't already been asked, but what would it take to add the ability to enable 'auto-refresh' feature?

**Comment by corey-hammerton** [comment]
That question/pull-request, indeed, has already been asked. https://github.com/puppet-community/puppetboard/pull/99

**Comment by fgimian** [comment]
I'll be looking at this in the next few days folks, hang tight :smile:

**Comment by corey-hammerton** [comment]
Implemented in 177f6c234a975afc80938385ee17448de89ad33b
