### ISSUE TITLE
Report status on node detail Reports section

### ISSUE THREAD

**Issue by jimr6007** [puppet-community/puppetboard#146]
Thanks for all the great work that has gone in to this project, we love Puppetboard at PlaceIQ !!

A feature request: (sorry if this is the wrong place to ask for this)

I'll occasionally see a failed node on the main page and then of course naturally I'll go to the node detail page and look at my last 20 reports.

It would be great if I could see in the column list of reports the status of each report - on the node detail page. Did just the last puppet run fail? Did this node start failing 3 hours ago. Did 5 failures in a row happen a few hours ago but now puppet runs are ok?

Thanks !

**Comment by corey-hammerton** [comment]
Pending review and additional testing I have fixed this in https://github.com/puppet-community/puppetboard/pull/176 which will show the same report status/event-count information that is available on the Overview page.

**Comment by jimr6007** [comment]
excellent thanks !, I'll try it out from your fork.

**Comment by jimr6007** [comment]
Hi Correy:

When I try the new Catalog feature I get the following error dump. Any idea what I might be doing wrong?

I cloned the repo and ran dev.py. I'm on Centos 7.1, Python 2.7.

And when I hit the overview tab/link I see:

ERROR:pypuppetdb.api:No such mbean puppet.nym1.placeiq.net:8081 over HTTPS.
INFO:werkzeug:10.1.200.189 - - [07/Nov/2015 18:47:47] "GET / HTTP/1.1" 404 -


my default_settings.py:


import os

PUPPETDB_HOST = 'puppet.nym1.placeiq.net'
PUPPETDB_PORT = 8081
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = '/etc/puppetboard/private.pem'
PUPPETDB_CERT = '/etc/puppetboard/public.pem'
PUPPETDB_TIMEOUT = 20
SECRET_KEY = os.urandom(24)
DEV_LISTEN_HOST = 'puppet.nym1.placeiq.net'
DEV_LISTEN_PORT = 5000
DEV_COFFEE_LOCATION = '/root/puppetboard/puppetboard/static/coffeescript'
UNRESPONSIVE_HOURS = 2
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
LOGLEVEL = 'info'
REPORTS_COUNT = 10
OFFLINE_MODE = False
ENABLE_CATALOG = True
GRAPH_FACTS = ['architecture',
               'domain',
               'lsbcodename',
               'lsbdistcodename',
               'lsbdistid',
               'lsbdistrelease',
               'lsbmajdistrelease',
               'netmask',
               'osfamily',
               'puppetversion',
               'processorcount']
INVENTORY_FACTS = [ ('Hostname',       'fqdn'              ),
                    ('IP Address',     'ipaddress'         ),
                    ('OS',             'lsbdistdescription'),
                    ('Architecture',   'hardwaremodel'     ),
                    ('Kernel Version', 'kernelrelease'     ),
                    ('Puppet Version', 'puppetversion'     ), ]






File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/puppetboard/puppetboard/app.py", line 418, in catalogs
order_by='[{"field": "certname", "order": "asc"}]')
File "/root/puppetboard/puppetboard/utils.py", line 23, in get_or_abort
return func(*args, **kwargs)
TypeError: nodes() got an unexpected keyword argument 'order_by'


Jim Richard  |  PlaceIQ <http://www.google.com/url?q=http%3A%2F%2Fwww.placeiq.com%2F&sa=D&sntz=1&usg=AFrqEzcYjZpDPyqW7feNK9EgLq-c9JlHiw>  |  Systems Administrator  |  jrichard@placeiq.com <mailto:name@placeiq.com>  |  +1 (646) 338-8905 <>

**Comment by corey-hammerton** [comment]
It looks like you are connecting to the HTTPS port (8081) but have PUPPETDB_SSL_VERIFY set to false. 

Can you try on the HTTP port (8080) or set PUPPETDB_SSL_VERIFY to True?

**Comment by daenney** [comment]
Connecting over HTTPS with PUPPETDB_SSL_VERIFY set to False is pretty common. That disables validating the PuppetDB SSL/TLS server certificate, it doesn't stop you from sending the client cert. If the rest of Puppetboard works, this shouldn't be an issue.

The problem seems to be `No such mbean` meaning we're requesting statistics/an mbean endpoint that doesn't exist.

**Comment by jimr6007** [comment]
right and in fact I run without SSL in production since I have puppetdb, puppetmaster and puppetboard all on the same host managing about 1000 nodes; I'll bet this is common for smaller shops like ours.

I only enabled SSL because I saw the same error when I initially tried without and saw essentially the same error, but with "mbean .... 8080 over HTTP.

Note that there are two issues I reported. Would you like me to start another for the problem of "TypeError: nodes() got an unexpected keyword argument 'order_by'" when I click the new Catalog link/tab?



Jim Richard  |  PlaceIQ <http://www.google.com/url?q=http%3A%2F%2Fwww.placeiq.com%2F&sa=D&sntz=1&usg=AFrqEzcYjZpDPyqW7feNK9EgLq-c9JlHiw>  |  Systems Administrator  |  jrichard@placeiq.com <mailto:name@placeiq.com>  |  +1 (646) 338-8905 <>

**Comment by daenney** [comment]
It seems to me you're mixing in a version of PuppetDB that's not supported by your release of Puppetboard. That's the only reason I can figure out why you'd get the mbean error and the order_by error.

Which versions of Puppetboard, pypuppetdb and PuppetDB are you running?

**Comment by jimr6007** [comment]
2.3.5 of PuppetDB - not ready to go to 3.X yet because that means Puppet 4.X, which is a huge upgrade as far as I can tell. I can upgrade to 2.3.8 of PuppetDB if you think that'll help.

0.0.5 for Puppetboard.

I was wondering about that. Does the new Catalog functionality of Puppetboard use PuppetDB end points only available with PuppetDB 3.X?

0.1.1 for Pypuppetdb


Here's my "pip list" output:

backports.ssl-match-hostname (3.4.0.2)
configobj (4.7.2)
decorator (3.4.0)
dnspython (1.11.1)
Flask (0.10.1)
Flask-WTF (0.9.5)
freeipa (2.0.0.alpha.0)
iniparse (0.4)
iotop (0.6)
ipaplatform (4.1.0)
ipapython (4.1.0)
itsdangerous (0.24)
javapackages (1.0.0)
Jinja2 (2.8)
kerberos (1.1)
lxml (3.2.1)
MarkupSafe (0.23)
netaddr (0.7.5)
pip (1.5.6)
puppetboard (0.0.5)
pyasn1 (0.1.6)
pycurl (7.19.0)
pygobject (3.8.2)
pygpgme (0.3)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pypuppetdb (0.1.1)
python-dateutil (1.5)
python-default-encoding (0.1)
python-ldap (2.4.15)
python-nss (0.16.0)
python-yubico (1.2.1)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
qrcode (5.0.1)
requests (2.7.0)
setuptools (0.9.8)
six (1.3.0)
slip (0.4.0)
slip.dbus (0.4.0)
SSSDConfig (1.12.2)
urlgrabber (3.10)
virtualenv (1.10.1)
Werkzeug (0.10.4)
wsgiref (0.1.2)
WTForms (1.0.5)
yum-metadata-parser (1.1.4)


Jim Richard  |  PlaceIQ <http://www.google.com/url?q=http%3A%2F%2Fwww.placeiq.com%2F&sa=D&sntz=1&usg=AFrqEzcYjZpDPyqW7feNK9EgLq-c9JlHiw>  |  Systems Administrator  |  jrichard@placeiq.com <mailto:name@placeiq.com>  |  +1 (646) 338-8905 <>

**Comment by corey-hammerton** [comment]
@jimr6007 Can you please create a new issue and include this information?

This issue is about another topic.

**Comment by corey-hammerton** [comment]
Report status on node details and report pages implemented in https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f

**Comment by jimr6007** [comment]
Sorry for the late response.

Indeed, after upgrading to PuppetDB 3.2.2, I'm not longer seeing this issue.

Thanks!


Jim Richard  |  PlaceIQ <http://www.google.com/url?q=http%3A%2F%2Fwww.placeiq.com%2F&sa=D&sntz=1&usg=AFrqEzcYjZpDPyqW7feNK9EgLq-c9JlHiw>  |  Systems Administrator  |  jrichard@placeiq.com <mailto:name@placeiq.com>  |  +1 (646) 338-8905 <>
