### ISSUE TITLE
UNRESPONSIVE_HOURS not working ?

### ISSUE THREAD

**Issue by glz-io** [puppet-community/puppetboard#148]
Hi,

I've installed "master version" and I still have a bug with UNRESPONSIVE_HOURS.

Set it to 4 for 4 hours:
root@... # grep UNRESPONSIVE_HOURS settings.py 
UNRESPONSIVE_HOURS = 4

But I still get unreported node with 2 hours.

![capture d ecran_2015-06-24_15-45-25](https://cloud.githubusercontent.com/assets/7238859/8331495/0121df64-1a89-11e5-984a-0a2b28c770fb.jpg)

Is it a known issue ?

**Comment by corey-hammerton** [comment]
Are you still experiencing this problem in 0.0.5?

**Comment by glz-io** [comment]
Hi,

The problem seems to be fixed. I'll wait a few hours to confirm as I not always have the problem due to random splay time in puppet.

**Comment by glz-io** [comment]
In fact, yes... I still have the problem with version 0.0.5.

i've restart gunicorn and delete any pyc file to be sure.

**Comment by corey-hammerton** [comment]
With that we will consider this issue closed.

**Comment by glz-io** [comment]
No no... I still have the problem.

**Comment by daenney** [comment]
I don't believe there's a bug in the code.

First we load the defaults:
```python
app.config.from_object('puppetboard.default_settings')
```

And then we load any additional settings by a file that we get pointed at with an environment variable:
```python
app.config.from_envvar('PUPPETBOARD_SETTINGS', silent=True)
```

If that file doesn't exist, we simply don't load it and I'm guessing it's currently being pointed at the wrong place.

The two places where we use it correctly query for it using:
```python
app.config['UNRESPONSIVE_HOURS'],
```

**Comment by glz-io** [comment]
Hi,

The problem was in my setup with gunicorn. Sorry for the noise.
