### ISSUE TITLE
reports tab still not enabled?

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppet-community/puppetboard#150]
reports page in puppetboard still says it doesn't work until https://tickets.puppetlabs.com/browse/PDB-201 is closed.
But that was closed with puppetdb-2.1.0 and now I'm running puppetdb-2.3.4 here.. 

What am I missing? :)

**Comment by corey-hammerton** [comment]
The Reports tab will be fully functional in the 0.1.0 release. No release date yet.

**Comment by corey-hammerton** [comment]
Please note https://github.com/puppet-community/puppetboard/pull/176

**Comment by corey-hammerton** [comment]
Reports tab enabled with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
