### ISSUE TITLE
noop mode visible for runs?

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppet-community/puppetboard#151]
Can it be viewed in puppetdb if an agent was run in noop mode?
When making large changes, I usually switch all nodes to run in noop mode (the puppet agent run script, curl's to a central url to fetch "noop" or not.. to decide what it runs it in), and it would be great to be able to see in puppetboard if runs registered are run in noop mode or not.. :)

**Comment by corey-hammerton** [comment]
PyPuppetDB 0.2.0 does successfully set noop states for nodes and reports. However, PuppetBoard 0.1.0 will support this when it is released.

**Comment by corey-hammerton** [comment]
This issue is related to https://github.com/puppet-community/puppetboard/issues/89

**Comment by corey-hammerton** [comment]
Fixed with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f, which requires PyPuppetDB >= 0.2.0 which successfully sets the noop status
