### ISSUE TITLE
Issues with connection on all in one install

### ISSUE THREAD

**Issue by Jmeyering** [puppet-community/puppetboard#152]
I'm running Puppet 4.2.0 on Ubuntu 14.04 Installed Puppetboard with apache and can hit the url it lives on just fine. However its having trouble connecting to the puppetdb that lives on the same server.

Here is my settings.py

```
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = 'localhost'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 3
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
PUPPETDB_EXPERIMENTAL = False
REPORTS_COUNT = 40
```

The error I'm receiving seems a little strange to me.

```
[Tue Jul 14 21:12:46.290186 2015] [:error] [pid 27563:tid 139926460798720] INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
[Tue Jul 14 21:12:46.294377 2015] [:error] [pid 27563:tid 139926460798720] ERROR:pypuppetdb.api: 127.0.0.1:8080 over HTTP.
```

The message that puppetboard is giving me is the 404 page 

````
Not Found
What you were looking for could not be found in PuppetDB.
```

Any thoughts on how to proceed debugging this?

**Comment by fabulops** [comment]
I ran into this issue yesterday. Seems Puppetlabs released v3 of PuppetDB which only supports the v4 API and makes backward compatible changes to the various URLs. For now at least, you can pin PuppetDB to version 2.3.5 since that works for Puppetboard.

**Comment by corey-hammerton** [comment]
Please watch for PuppetBoard release 0.1.0 which will only support PuppetDB v4 Query API

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/puppetboard/pull/176 has been opened. The 0.1.0 release will soon follow its merge.

**Comment by corey-hammerton** [comment]
Fixed in https://github.com/puppet-community/puppetboard/commit/7f520af66107b937aaf418946a1ab7199ab267d3
