### ISSUE TITLE
Puppetboard 2.5.0 with Puppetdb 3.0 and puppet 4.2

### ISSUE THREAD

**Issue by wooziethe** [puppet-community/puppetboard#154]
Hello,

Im experiencing problems with getting content in puppetboard. Im getting following errors when opening "overwiev" or other tabs:

tail -f -n 600 /var/log/apache2/puppet-test_error.log
[error] INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): puppet-test[error] ERROR:pypuppetdb.api: puppet-test:8081 over HTTPS.

tail -f -n 600 /var/log/puppetlabs/puppetdb/puppetdb-access.log
 "GET /v3/metrics/mbean/com.puppetlabs.puppetdb.query.population:type=default,name=num-nodes HTTP/1.1" 404 0 "-" "python-requests/2.2.1 CPython/2.7.3 Linux/3.2.0-4-amd64"

Ive installed puppetboard and all its dependencies from a module. puppetdb and pupetboard are on the same machine. Puppetdb works on 8081. Site.pp looks like this:

node 'puppet-test' {
class { 'apache': }
class { 'apache::mod::wsgi': }
class { 'puppetboard':
manage_git        => true,
manage_virtualenv => true,
puppetdb_host => 'puppet-test',
puppetdb_port => '8081',
puppetdb_key  => "/etc/puppetlabs/puppetdb/ssl/private.pem",
puppetdb_ssl  => 'True',
puppetdb_cert => "/etc/puppetlabs/puppetdb/ssl/public.pem",
}
class { 'puppetboard::apache::vhost':
vhost_name => 'puppet-test',
port       => 80,
}
}

I found this article about /v3/metrics in new puppetdb:
"•(3.0) The former metrics endpoint has been split off into a separate service, and reversioned at v1. This means if you are currently accessing mbeans at http://localhost:8080/v3/metrics/mbeans, you will now access them at http://localhost:8080/metrics/v1/mbeans and so on according to the metrics api documentation.
•(3.0) PuppetDB’s mbeans (listed at /metrics/v1/mbeans) are no longer prefixed with “com.”"
https://docs.puppetlabs.com/puppetdb/latest/api/query/v4/upgrading-from-v3.html

Another type of error im getting when opening "Inventory tab":

tail -f -n 600 /var/log/apache2/puppet-test_error.log
[error] ERROR:pypuppetdb.api: puppet-test:8081 over HTTPS.
[error] ERROR:puppetboard.app:Exception on /inventory [GET]
[error] Traceback (most recent call last):
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[error]     response = self.full_dispatch_request()
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[error]     rv = self.handle_user_exception(e)
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[error]     reraise(exc_type, exc_value, tb)
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[error]     rv = self.dispatch_request()
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[error]     return self.view_functions[rule.endpoint](**req.view_args)
[error]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 224, in inventory
[error]     for fact in facts:
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pypuppetdb/api/v3.py", line 136, in facts
[error]     facts = self._query('facts', path=path, query=query)
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pypuppetdb/api/__init__.py", line 267, in _query
[error]     r.raise_for_status()
[error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
[error]     raise HTTPError(http_error_msg, response=self)
[error] HTTPError: 404 Client Error: Not Found

tail -f -n 600 /var/log/puppetlabs/puppetdb/puppetdb-access.log
"GET /v3/facts?query= HTTP/1.1" 404 0 "-" "python-requests/2.2.1 CPython/2.7.3 Linux/3.2.0-4-amd64"

What can be done to solve this?

Regards,
Alex

**Comment by corey-hammerton** [comment]
This version of puppetboard and the pypuppetdb python library it runs on is not compatible with PuppetDB 3.x and the query api v4. Work is being done to add support to it but it is still under development.

**Comment by wooziethe** [comment]
Thanks for the info!

Regards,
Alex

**Comment by AxisNL** [comment]
Aaaaah noo! I just spent a day on setting up puppetboard, just to find out it doesn't work with my recent puppet installation.. Well, at least the screenshots of the project look nice! :smile: 

Do you have an ETA on a new version that should work? I understand you might not have an exact date, but do you expect this to take days, weeks or months? :)

**Comment by Jmeyering** [comment]
:+1:  Hoping this can be implemented soon :)

**Comment by corey-hammerton** [comment]
Although I haven't been able to work on it recently, the pypuppetdb library development work should be finished within the next few weeks. Then I would be able to start work on my own fork for the puppetboard. 

If anybody is interested in contributing work you can fork my branch https://github.com/corey-hammerton/pypuppetdb/tree/puppetdb-3.0

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/pypuppetdb/pull/55 has just been opened. Keep in mind this is just the initial development work, I do not have any influence on releases of this library.

**Comment by corey-hammerton** [comment]
Pypuppetdb 0.2.0 has been released this week with full Query API v4 support. NOTE: support for the v2 and v3 APIs have been removed.

PuppetBoard is still under development for a 0.1.0 release which includes Query API v4 support. Please stay tuned.

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/puppetboard/pull/176 resolves this issue.

**Comment by corey-hammerton** [comment]
Fixed in https://github.com/puppet-community/puppetboard/commit/7f520af66107b937aaf418946a1ab7199ab267d3
