### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by JohnHwee** [puppet-community/puppetboard#155]
After I installed puppetboard with pip install puppetboard, how can I run it?

**Comment by bastelfreak** [comment]
Have you already read the [Readme](https://github.com/puppet-community/puppetboard#configuration)? Which points are unclear to you?

**Comment by daenney** [comment]
This is extensively documented in the README including configuration samples on how to load this on Apache and nginx with a multitude of examples for different application servers like mod_wsgi, Passenger, uwsgi and gunicorn.

If there's still something unclear after having read that please open up a new issue with a more detailed explanation of what you do not understand and we can address that.
