### ISSUE TITLE
ArchLinux package is gone

### ISSUE THREAD

**Issue by tuxinaut** [puppet-community/puppetboard#165]
The ArchLinux package **Maintained by Niels Abspoel** is gone the link responds with a 404.

**Comment by daenney** [comment]
What do you expect as an outcome? We currently don't maintain that package :smile:

**Comment by bastelfreak** [comment]
@tuxinaut I added [python2-puppetboard](https://aur.archlinux.org/packages/python2-puppetboard/), [python-pypuppetdb and python2-pypuppetdb](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=puppetdb&outdated=&SB=n&SO=a&PP=50&do_Search=Go) to the AUR4 and will shortly move it into the official community repo.

**Comment by tuxinaut** [comment]
Thank you for be the new maintainer for this package :+1:
