### ISSUE TITLE
Node status index links don't play nice with wsgi_alias

### ISSUE THREAD

**Issue by bwithem** [puppet-community/puppetboard#171]
### puppetboard/puppetboard/templates/index.html
Node status links don't play nice with a ```wsgi_alias```, can these reference endpoints and use ```url_for()```?

```
{% extends 'layout.html' %}
{% block content %}
<div class="ui vertical grid">
  <div class="four column row">
    <div class="column">
      <a href="nodes?status=failed">
```

**Comment by corey-hammerton** [comment]
Included in https://github.com/corey-hammerton/puppetboard/commit/987e93d10ba3f42bcb689f19d761fc0440a791c4#diff-56e2c962750657ba349b583ffb928df2

**Comment by corey-hammerton** [comment]
Fixed with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
