### ISSUE TITLE
Internal Server Error when trying to view Reports (PuppetDB v3.2, puppetboard v0.1)

### ISSUE THREAD

**Issue by peelman** [puppet-community/puppetboard#179]
Was anxiously awaiting this morning's release of 0.1 so I could start using puppetboard.

Everything is installed and fully updated through pip (pypuppetdb, puppetboard, etc).  Using apache2 and mod_wsgi to server the site, with an almost identical vHost to what's in the README.

Overview, Nodes, Facts, and Metrics all seems to work fine.  But reports generates an Internal Server Error:

	ERROR:puppetboard.app:Exception on /reports/ [GET]
	[Tue Nov 10 10:53:10.928894 2015] [:error] [pid 23342:tid 139908660311808] Traceback (most recent call last):
	[Tue Nov 10 10:53:10.929037 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
	[Tue Nov 10 10:53:10.929197 2015] [:error] [pid 23342:tid 139908660311808]     response = self.full_dispatch_request()
	[Tue Nov 10 10:53:10.929336 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
	[Tue Nov 10 10:53:10.929473 2015] [:error] [pid 23342:tid 139908660311808]     rv = self.handle_user_exception(e)
	[Tue Nov 10 10:53:10.929686 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
	[Tue Nov 10 10:53:10.929825 2015] [:error] [pid 23342:tid 139908660311808]     reraise(exc_type, exc_value, tb)
	[Tue Nov 10 10:53:10.929881 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
	[Tue Nov 10 10:53:10.929927 2015] [:error] [pid 23342:tid 139908660311808]     rv = self.dispatch_request()
	[Tue Nov 10 10:53:10.929969 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
	[Tue Nov 10 10:53:10.930011 2015] [:error] [pid 23342:tid 139908660311808]     return self.view_functions[rule.endpoint](**req.view_args)
	[Tue Nov 10 10:53:10.930936 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 382, in reports
	[Tue Nov 10 10:53:10.931074 2015] [:error] [pid 23342:tid 139908660311808]     for report in reports_events:
	[Tue Nov 10 10:53:10.931210 2015] [:error] [pid 23342:tid 139908660311808]   File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/__init__.py", line 781, in reports
	[Tue Nov 10 10:53:10.931476 2015] [:error] [pid 23342:tid 139908660311808]     metrics=report['metrics']['data'],
	[Tue Nov 10 10:53:10.931682 2015] [:error] [pid 23342:tid 139908660311808] KeyError: u'data'

I get a similar error when trying to use Catalog to do a compare.

Just wanting to see if this was a glitch or a screwup on my part...

**Comment by corey-hammerton** [comment]
Can you try a manual CURL on the reports endpoint of your PuppetDB server?

I just want to make sure that the report format has a 'metrics' key with a 'data' key under it.

**Comment by peelman** [comment]
Certainly.

	root@puppet:/etc/puppetlabs/code/environments/production# curl http://localhost:8080/pdb/query/v4/reports
	[ {
	  "receive_time" : "2015-11-09T21:23:48.295Z",
	  "hash" : "78eedfcb26459ed7c68558920b7353f03fc12ce6",
	  "transaction_uuid" : "ab392176-a281-4bdf-a0f6-c29a94c70d7f",
	  "puppet_version" : "3.8.4",
	  "noop" : false,
	  "logs" : {
	    "href" : "/pdb/query/v4/reports/78eedfcb26459ed7c68558920b7353f03fc12ce6/logs"
	  },
	  "report_format" : 4,
	  "start_time" : "2015-11-09T21:23:36.408Z",
	  "producer_timestamp" : "2015-11-09T21:23:48.142Z",
	  "end_time" : "2015-11-09T21:23:42.955Z",
	  "resource_events" : {
	    "href" : "/pdb/query/v4/reports/78eedfcb26459ed7c68558920b7353f03fc12ce6/events"
	  },
	  "status" : "unchanged",
	  "configuration_version" : "1447104226",
	  "environment" : "production",
	  "certname" : "testbed.domain.com",
	  "metrics" : {
	    "href" : "/pdb/query/v4/reports/78eedfcb26459ed7c68558920b7353f03fc12ce6/metrics"
	  }

It would appear no?

**Comment by corey-hammerton** [comment]
While you are running PuppetDB 3.2 your Puppet agent is running version 3.8.4. 

You will have to upgrade your puppet agent in order to resolve this.

**Comment by peelman** [comment]
That was an old run i pulled from the top.  here's a later one, showing puppet 4.2 doing the same thing:

	{
	  "receive_time" : "2015-11-10T16:18:37.980Z",
	  "hash" : "8d168133f8f34220fe6274a7afd643bc431f65c7",
	  "transaction_uuid" : "f3a82e63-9505-4853-bca0-44f107074c84",
	  "puppet_version" : "4.2.3",
	  "noop" : false,
	  "logs" : {
	    "href" : "/pdb/query/v4/reports/8d168133f8f34220fe6274a7afd643bc431f65c7/logs"
	  },
	  "report_format" : 4,
	  "start_time" : "2015-11-10T16:18:22.543Z",
	  "producer_timestamp" : "2015-11-10T16:18:37.942Z",
	  "end_time" : "2015-11-10T16:18:29.663Z",
	  "resource_events" : {
	    "href" : "/pdb/query/v4/reports/8d168133f8f34220fe6274a7afd643bc431f65c7/events"
	  },
	  "status" : "changed",
	  "configuration_version" : "1447172309",
	  "environment" : "production",
	  "certname" : "testbed.domain.com",
	  "metrics" : {
	    "href" : "/pdb/query/v4/reports/8d168133f8f34220fe6274a7afd643bc431f65c7/metrics"
	  }

**Comment by corey-hammerton** [comment]
Looking at the Puppet documentation they note that the data field is only expanded on a PostgreSQL backend. Am I correct to assume that you are using an HSQLDB backend?

**Comment by peelman** [comment]
You were indeed correct to assume that.  Its great that the puppet labs puppetdb installer package defaults to a driver and/or database they have deprecated and doesn't support several of the features...

If I amend the readme to explain this a little more to n00bs like myself, would you be amendable to the pull request?

**Comment by corey-hammerton** [comment]
@peelman Please create an issue in https://github.com/puppet-community/pypuppetdb/issues with all this information. 

This is an issue related to pypuppetdb rather than puppetboard.

**Comment by peelman** [comment]
I'm confused; what am I filing against pypuppetdb that would be wrong?  just looking for a more graceful failure?

**Comment by corey-hammerton** [comment]
The issue is that pypuppetdb is looking for expanded metric and log information that is only available on PostgreSQL backends. You are using an HSQLDB backend that does NOT directly provide this information.

This information CAN be found in HSQLDB but a code patch must be done in pypuppetdb.

**Comment by peelman** [comment]
Ah, ok. I'll write something up over there after lunch. 

Thanks for the hand holding and patience. Python apps are not a line item on my resume yet :)

**Comment by daenney** [comment]
https://docs.puppetlabs.com/puppetdb/latest/configure.html#using-hsqldb

> Note that support for HSQLDB has been deprecated and will be removed in a future release. Please see this email to the puppet-users list for further information.

**Comment by corey-hammerton** [comment]
I suppose the question now is should we patch pypuppetdb if HSQLDB is already deprecated. My answer is no.

**Comment by daenney** [comment]
I agree. I don't think it makes sense to add a patch to support a backend that's going away soon.

**Comment by peelman** [comment]
So yeah...might I resuggest adding a note or word of caution to the Readme for other newcomers to PuppetDB who are moving away from PuppetDashboard and to PuppetDB/PuppetBoard as they migrate to Puppet 4 that the default configuration of puppetDB is using HSQLDB and obviously that presents other issues going forward.  I understand this problem doesn't apply to you guys directly; but a note up front would save a lot of time for those of us who don't do python web apps every day.
