### ISSUE TITLE
Report links don't include environment

### ISSUE THREAD

**Issue by gotyaoi** [puppet-community/puppetboard#181]
Using puppetboard 0.1 and pypuppetdb 0.2.

When having a environment set and going to the reports tab, or clicking the reports button from the nodes tab, the links to the individual reports will not include the environment prefix. For example, If I have an environment "cluster" and a host "app1.example.com" and go to "/cluster/reports/app1.example.com", the links to the individual reports will be like "/report/app1.example.com/report_id", when it should be "/cluster/report/app1.example.com/report_id", and will return 404.

**Comment by corey-hammerton** [comment]
Thanks for reporting this @gotyaoi a Pull Request has just been submitted to fix this bug.
