### ISSUE TITLE
Static Environment List

### ISSUE THREAD

**Issue by octomike** [puppet-community/puppetboard#186]
Creating and pushing new branches/environments to our puppet server now requires to reload the uwsgi process as the environment list is assembled globally upon puppetboard start.
This is very unfortunate and kind of kills our workflow. Three "solutions" come to mind:

1. reload uwsgi every time we push to our puppet repo

2. add patch to globally disable environment based views

3. add patch to reload environment list on every request

What do you recommend we should do?

**Comment by octomike** [comment]
I found another "feature".
It looks like puppetdb keeps environments as long as there are resources or reports available even though there are no nodes left in that environment. I'm not sure if this is useful for some people. If not we could check `/pdb/query/v4/environments/<ENVIRONMENT>/facts` for each environment and skip it if the result comes up empty.

**Comment by corey-hammerton** [comment]
@octomike I do not think that this latest approach is the best way because it brute-forces the PuppetDB. Users will be better off adjusting the setting of the node-purge-ttl setting in their PuppetDB configurations.

**Comment by corey-hammerton** [comment]
As for the initial solutions I would rather update the code to reload the environment list on every request. 

Reloading the uwsgi process is not possible programmatically because each environment may be set up different. Globally disabling environments is also not advisable because Puppet is completely environment based now and would not make much sense to reverting this approach (there are active PRs to update the environment functionality now)

**Comment by octomike** [comment]
You're right, I overlooked the pull requests, specifically #185.

The "stale" environment issue still exists though. Lowering node-purge-ttl does not seem to be a solution at a first glance. How would we be able to track unreported nodes for multiple days and at the same time purge empty (no nodes left) environments very quickly ?

**Comment by corey-hammerton** [comment]
PuppetDB has a Garbage Collector that runs every 60 minutes by default but configurable via [gc-interval.](http://docs.puppetlabs.com/puppetdb/3.2/configure.html#gc-interval) This process will clean up any deactivated nodes after ``node-purge-ttl`` expires as well as any facts, catalogs and environments. 

You can lower the value of this setting if you require it.

**Comment by octomike** [comment]
In our environment-centric workflow nodes move between environments quite quickly.
Even with a low setting of gc-interval our (temporary) development environments pollute puppetboard as they won't be removed because at least report-ttl is deliberately kept at the default (14d).
I guess I am questioning if it makes sense for puppetboard to keep listing reports and catalogs for empty environments.

**Comment by corey-hammerton** [comment]
No matter how we try to suppress environments with no active nodes it still doesn't hide the fact that they still exist in PuppetDB and PuppetBoard only reports on what's present in PuppetDB. 

We will submit a code patch to check the environments on each page load so you won't have to reload uwsgi all the time.

**Comment by corey-hammerton** [comment]
@octomike I have created https://github.com/puppet-community/puppetboard/issues/189 to fix this issue. Please stay tuned for the 0.1.2 release.
