### ISSUE TITLE
Does Puppetboard 0.1.1 works with Puppetdb 2.3x?

### ISSUE THREAD

**Issue by jlory** [puppet-community/puppetboard#188]
I'm asking because I installed those two and Puppetboard tries to query for v4 api: GET /pdb/query/v4/environments HTTP/1.1 and get a 404 not found.

Is there a setting to specify the API version of puppetdb to use?

Edit: pypuppetdb : Removing v2 and v3 api functions as per changelog

**Comment by mcanevet** [comment]
no it does not

**Comment by jlory** [comment]
I don't understand is it the intended behavior? pip install puppetboard installs the last version that doesn't work with Puppetdb 2.3.x, most people use this version. There should be some warning somewhere saying that version is not compatible with 90% of Puppet installation.

**Comment by corey-hammerton** [comment]
You can run ``pip install -U pupetboard-0.0.5`` to install the latest Puppetboard version THAT WORKS with PuppetDB 2.3. 

Starting with puppetboard 0.1.0 and pypuppetdb 0.2.0 we have removed support for PuppetDB < 3.0 because PuppetDB 3.0 has remove support for those legacy Query API versions.

**Comment by daenney** [comment]
> I don't understand, is it the intended behavior? pip install puppetboard installs the last version that doesn't work with Puppetdb 2.3.x, most people use this version. There should be some warnings somewhere saying that this version is not compatible with 90% of Puppet installation.

And where exactly did you get that 90% from? Also, when you install Puppetboard we have no way of detecting your PuppetDB version so we can't really do much with warnings. We could have it throw an error page at you once it tries to connect to PuppetDB and the servers don't match but that's an extra API request per page render that's not really worth it.

> You should at least mention the removal of supported versions in the changelog.

Yes, that ought to be added to the CHANGELOG and README.

**Comment by jlory** [comment]
Thank you, I'm closing the issue. For the 90% yes most people use Puppetdb 2.x because newer version requires Puppet 4 and version 4 is very recent and requires the client and the server to use the new packages ( which is a big change for most people )

**Comment by corey-hammerton** [comment]
We completely understand that. We should also clearly state that 0.0.5 does support PuppetDB 2.x to avoid this kind of confusion.

**Comment by nibalizer** [comment]
How hard is it to have puppetboard detect and give a useful error?

**Comment by janorn** [comment]
Perhaps a setup phase? On the first run. I do believe that many users will stay for a while on puppetdb 2.3. We are not ready for puppet 4 yet. We are still migrating from 2.7.

**Comment by corey-hammerton** [comment]
We could do a version check in puppetboard right after it connects to the PuppetDB and have it throw a 500 error. Would have to modify that template to state the incompatibility.

**Comment by daenney** [comment]
Connecting to PuppetDB is not part of any route, it's done when loading the application. You can't really throw an http response from there.

**Comment by jlory** [comment]
Some work can be done using the /version endpoint:

http://docs.puppetlabs.com/puppetdb/2.3/api/query/v3/version.html

**Comment by corey-hammerton** [comment]
I'm still in favour of clearly stating that 0.1.0 and above does not work with PuppetDB <= 2.3.8

**Comment by daenney** [comment]
Yeah. Adding these kinds of compatibility checks will become hairy over time. The continuous check for PuppetDB API version compatibility is really unnecessary. We can potentially modify pypuppetdb to do the check the first time connect is called and throw an exception which can then be handled in Puppetboard. But patching this in Puppetboard is not a good idea. The information has been added to the README and CHANEGLOG, that should suffice for now.
