### ISSUE TITLE
Pie Charts in Facts view

### ISSUE THREAD

**Issue by rkcpi** [puppet-community/puppetboard#190]
Some facts like architecture have a pie chart in their facts view that displays the distribution of the different values. It would be nice to have this pie chart for all facts. I still can't figure out, when a pie chart is displayed and when not.

**Comment by corey-hammerton** [comment]
A pie chart is displayed for a fact when the fact is in the ``GRAPH_FACTS`` configuration setting in ``default_settings.py``

I agree that it would be nice to re-implement pie charts for all facts it would not make sense for ip address, MAC address and UUID facts as well as all the JSONified facts which we can't effectively browse through yet. Each one of them will probably be unique for each host.

**Comment by rkcpi** [comment]
Agreed, it doesn't make sense for facts that are unique for each host. But lots of other facts would be cool with pie charts, for example puppet version, operating system, ..

**Comment by corey-hammerton** [comment]
Those fact names simply need to be added to the ``GRAPH_FACTS`` setting in ``default_settings.py``

**Comment by nibalizer** [comment]
The plan when we made this compromise was to be very generous with PRs adding facts to graph in default_settings.py

**Comment by corey-hammerton** [comment]
You can list out all the facts you want graphed in the ``GRAPH_FACTS`` setting in your ``default_settings.py``
