### ISSUE TITLE
pip package (0.1.1) actually installs version v0.1.0

### ISSUE THREAD

**Issue by jbehrends** [puppet-community/puppetboard#194]
Just installed puppetboard using pip with apache and found that the v0.1.1 packing is actually installing v0.1.0

$ pip list |grep puppetboard
puppetboard (0.1.1)

Screen capture of the top bar with version. 
![image](https://cloud.githubusercontent.com/assets/1915783/11449789/4fb2b552-9538-11e5-8c52-6d47fe621f68.png)

**Comment by corey-hammerton** [comment]
That was an oversight in the layout template when 0.1.1 was released, you indeed have 0.1.1 installed.

**Comment by jbehrends** [comment]
Are you 100% sure?  I installed puppetboard two days ago directly from master, and this looks a tad different.  In fact the install from pip also does not look like example pics from the main README file:

![image](https://cloud.githubusercontent.com/assets/1915783/11449915/17e7be50-953e-11e5-8277-933f1c671f85.png)

AND 

![image](https://cloud.githubusercontent.com/assets/1915783/11449920/293bccd2-953e-11e5-9b64-b27ff6106a9c.png)

**Comment by corey-hammerton** [comment]
You're talking to the guy who released both those updates. 

The only difference between 0.1.0 and 0.1.1 is the Reports tab is properly setting the environment in the links to the individual reports. In fact 0.1.0 is hidden from PIP so you cannot install 0.1.0 through PIP.

The README screen shots were taken in the 0.0.4 and 0.0.5 days and were never updated. 

The alignment in the status block, however, may be a legitimate issue, could you include the second screen shot in a new issue we can investigate.

**Comment by jbehrends** [comment]
Sounds good to me!  Thanks for all of the clarification!
