### ISSUE TITLE
Catalog tab comparison reuslts not properly aligned

### ISSUE THREAD

**Issue by llowder** [puppet-community/puppetboard#200]
When comparing two catalogs on the catalog tab, in the Resources, for the "compared to" node, there is a very large section of white space before the resources are shown, and this amount of white space varies depending on which nodes are being compared.

This makes it very difficult to be able to use this, otherwise awesome feature

**Comment by corey-hammerton** [comment]
This duplicates https://github.com/puppet-community/puppetboard/issues/193
