### ISSUE TITLE
Request 'all environments' (aggregated) view of all nodes in PuppetDB

### ISSUE THREAD

**Issue by ryebread157** [puppet-community/puppetboard#205]
I am a heavy user of puppetboard and am testing out the new version with puppet4/puppetdb3. A 'feature' of older puppetdb/puppetboard is that all puppet nodes--from all environments--all show up. From what little I have read and observe, PuppetDB3 heavily classifies nodes by their environment, which may explain the puppetboard requirement to select an environment.

Could a new drop-down, like Environments --> All Environments, be added that would provide a view that shows nodes/facts/reports for all nodes in PuppetDB? This would be quite helpful in providing both technical and non-technical (ie management) people who use puppetboard answers to questions the older puppetboard provided. Thanks.

**Comment by corey-hammerton** [comment]
This request has been implemented with https://github.com/puppet-community/puppetboard/pull/185/files. It awaits the 0.1.2 release.

**Comment by ryebread157** [comment]
Excellent! I looked at open/closed issues and wasn't able to see a similar request. Thanks much for your work on puppetboard, it is extremely useful.
