### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by daenney** [puppet-community/puppetboard#60]
Next release really needs to support pagination, this is getting ridiculous.

**Comment by b2jrock** [comment]
It looks like the upstream ticket is closed on this, any other blockers, aside from time to work on it?

**Comment by daenney** [comment]
It's not. The ticket is closed, the code never landed.

**Comment by b2jrock** [comment]
Ok, thanks for the clarification. I was hoping...

**Comment by corey-hammerton** [comment]
The new Pull Request is https://github.com/puppet-community/pypuppetdb/pull/47

**Comment by corey-hammerton** [comment]
PyPuppetDB 0.1.0 now supports paging parameters for all applicable endpoint functions. The planned 0.1.0 release of PuppetBoard will make use of this. 

If anybody wants to test https://github.com/puppet-community/puppetboard/pull/176

**Comment by corey-hammerton** [comment]
Initial implementation in https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f. Still a bit rudimentary but there is room for improvement.
