### ISSUE TITLE
Environment Awareness

### ISSUE THREAD

**Issue by kbarber** [puppet-community/puppetboard#64]
We are adding environmental awareness to PuppetDB and this tool should support that when it comes out.

For now this is targeted at PDB 2.0.0, which is targeted for a final release late May.

Here is the Epic covering this task: https://tickets.puppetlabs.com/browse/PDB-47

The docs will become available here as the feature progresses: http://docs.puppetlabs.com/puppetdb/master/

**Comment by arifsaha** [comment]
Hi!

Just wondering how is the progress on recognizing environment? Or in the mean time, are there any work around to allow PuppetBoard to display only single environment only?

Thank you!

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/puppetboard/pull/176 includes environment awareness by prefixing all paths with /<env> which filters all applicable queries based on the current environment. If the env value is not set use 'production' as the default.

**Comment by corey-hammerton** [comment]
This issue relates to https://github.com/puppet-community/puppetboard/issues/90

**Comment by corey-hammerton** [comment]
Implemented with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
