### ISSUE TITLE
Sorting by catalog or report timestamp does not work

### ISSUE THREAD

**Issue by boyand** [puppet-community/puppetboard#88]
Hey, 

Sorting nodes by catalog or report timestamp on the "Nodes" page does not work for some reason. The table keeps getting sorted by Hostname. This is quite an important functionality when it comes to tracking change propagation and rolling updates. 

I tried bump-ing the tablesorter version and playing with the date formatting without success. 

I am using the latest master and Firefox 31.0. Let me know if you need any additional info.

**Comment by fgimian** [comment]
I'm currently working on this and have almost got it, should have a pull request soon :smile:

**Comment by fgimian** [comment]
This has now been resolved with commit https://github.com/puppet-community/puppetboard/commit/fd351f44831b5101a1a059d1806890935133ff56 :smile:
