### ISSUE TITLE
Status for pending changes - noop

### ISSUE THREAD

**Issue by esbjerg** [puppet-community/puppetboard#89]
It would be really nice if the status button could show Pending instead of None when there are changes pending. This is really useful when the puppet agents run in noop mode per default.

If the color of the button could also change to something else than grey when this happens it would be really nice.

**Comment by tgc** [comment]
I just installed puppetboard from HEAD and also had this issue with noop events.
The problem looks to be that the pypuppetdb available on pypi (0.1.1) does not include this commit:
https://github.com/puppet-community/pypuppetdb/commit/3ab9da999ac53dc7c8dea7a8a9be4802c9f16042

With that commit applied I now see noop reports counting as pending and being listed in blue as noop in the overview (as intented by https://github.com/puppet-community/puppetboard/pull/69)

**Comment by corey-hammerton** [comment]
PyPuppetDB 0.2.0 correctly sets a node or report's status to noop if the flag is it. This is only supported in PuppetDB 3.0 and up. 

PuppetBoard will support this with the 0.1.0 release, stay tuned.

**Comment by corey-hammerton** [comment]
Noop status properly set with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
