### ISSUE TITLE
Ability to filter nodes by environment

### ISSUE THREAD

**Issue by sorrison** [puppet-community/puppetboard#90]
It would be really handy if you could filter nodes by environment. In the overview and the nodes view.

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/puppetboard/pull/176 filters all applicable endpoint results by environment. This will be released with 0.1.0

**Comment by corey-hammerton** [comment]
Environment awareness and filtering implemented with https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
