### ISSUE TITLE
More info available for the report page?

### ISSUE THREAD

**Issue by shanemadden** [puppet-community/puppetboard#92]
The last thing that's keeping us from turning off Puppet Dashboard and just using PuppetBoard is the extra detail that's provided in the Dashboard display of a report:

 - Log entries; which I think are not available in PuppetDB's API (maybe also not stored there at all?)
 - Time counters for each resource type; again, not seeing anywhere in the PuppetDB API to fetch this
 - List of all resources (I guess "events" in the API?), including unchanged, which is handy for troubleshooting of "did this resource not get put in the catalog like I expected, or is it there but just unchanged?" - it seems like these would be available, maybe collapse or hide them by default?

Are my guesses at API availability for these correct?  We'd like to avoid losing useful info when we put Dashboard out to pasture, so adding any of these would be handy for us.  Great work on PuppetBoard by the way! :+1:

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/puppetboard/pull/176 does list a report's log and metric information on the reports page. Please stay tuned for the 0.1.0 release.

**Comment by corey-hammerton** [comment]
Report logs and metrics displayed on report details page in https://github.com/puppet-community/puppetboard/commit/709480a83f79effaf4039817dba0a74bd03d5f0f
